### PR TITLE
Fix empty image issue by considering status code &separate WEBCAMS (dict) as a json file

### PR DESCRIPTION
**Pull request by hibetterheyj**
Thanks for your amazing code to get the images from roundshot!
When I run the code to extract starting from 2021-12-25_00-00, the original script may create an empty image when the status code equals 404. So I mainly update in following aspects

1. add an if-else condition to determine the status of the response.
2. separate `WEBCAMS` (dict) from `main.py` into `webcams.json` to increase scalability so as to add more links.

Some minor changes are:

1. format the code with [black](https://github.com/psf/black)
2. update `img_path` prefix with `quality`
3. check `img_path` existing or not before `GET` request
4. add `time.sleep(10)` to avoid `429 Too Many Requests` error

### CODE REVIEW

**Comment by mudpriest** [comment]
thank you a lot for the merge request!
To be honest, I was aware that the code was a little broken, but did not have have enough motivation to fix it 😅

**Comment by hibetterheyj** [comment]
No worries🙌Thanks a lot for your codebase so that I could have a quick start to extract images from roundshot to construct personal dataset for research use.

**Comment by mudpriest** [comment]
What are you researching, if you don't mind me asking? It sounds quite interesting.

**Comment by hibetterheyj** [comment]
It is related to place recognition for robots. I would like to extract the images in different seasons to construct a new database. Thanks again for your code 😄

**Pull request merged**
